using System.Collections.Concurrent;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Karambolo.PO;

namespace InkLocalizer.TableOutputs;

public class PotHandler(Localizer localizer, TableOutputOptions? options = null)
{
	private UTF8Encoding utf8WithoutBom = new UTF8Encoding(false);
	private readonly TableOutputOptions _options = options ?? new TableOutputOptions();
	private static string EscapePoString(string input)
	{
		if (input.IndexOfAny(['\\', '"', '\n']) == -1)
			return input; // 无需转义
		return input.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");
	}
	private void ExportDictionaryToPot(Dictionary<string, string> dict, string path)
	{
		// 预估大小：每条翻译大约 100 字节，初始容量设为合理值，避免多次扩容
		var sb = new StringBuilder(capacity: dict.Count * 100);

		// 写入 POT 头部
		sb.AppendLine("# POT file generated by Godot");
		sb.AppendLine("msgid \"\"");
		sb.AppendLine("msgstr \"\"");
		sb.AppendLine("\"Content-Type: text/plain; charset=UTF-8\\n\"");
		sb.AppendLine();

		// 批量构建每个条目
		foreach (var kvp in dict)
		{
			var msgid = EscapePoString(kvp.Key);

			sb.Append("msgid \"").Append(msgid).AppendLine("\"");
			sb.AppendLine("msgstr \"\"");
			sb.AppendLine();
		}
		// 一次写入文件
		using var file = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None);
		using var writer = new StreamWriter(file, utf8WithoutBom);
		writer.Write(sb.ToString());
	}
	private Dictionary<string, string> ExportDictionaryToPo(Dictionary<string, string> dict, string path, string languageCode)
	{
		// 预估大小：每条翻译大约 100 字节，初始容量设为合理值，避免多次扩容
		var sb = new StringBuilder(capacity: dict.Count * 100);

		// 写入 PO 头部
		sb.AppendLine($"# PO file for language: {languageCode}");
		sb.AppendLine("msgid \"\"");
		sb.AppendLine("msgstr \"\"");
		sb.AppendLine($"\"Language: {languageCode}\\n\"");
		sb.AppendLine("\"Content-Type: text/plain; charset=UTF-8\\n\"");
		sb.AppendLine();

		// 批量构建每个条目
		foreach (var kvp in dict)
		{
			string msgid = EscapePoString(kvp.Key);
			string msgstr = EscapePoString(kvp.Value);

			sb.AppendLine($"msgid \"{msgid}\"");
			sb.AppendLine($"msgstr \"{msgstr}\"");
			sb.AppendLine();
		}

		var targetParser = new POParser(new POParserSettings
		{
			// parser options...
		});
		var target = targetParser.Parse(sb.ToString());
		Dictionary<string, string> needTranslateDictionary = [];
		if (File.Exists(path))
		{
			string content = "";
			{
				using var fileReadWrite = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.None);
				using var reader = new StreamReader(fileReadWrite, utf8WithoutBom);
				content = reader.ReadToEnd();
			}
			var originParser = new POParser(new POParserSettings
			{
				// parser options...
			});
			var origin = originParser.Parse(content);
			// 合并 file2 到 file1（后者覆盖前者）
			foreach (var entry in target.Catalog.Keys)
			{
				POKey? existing = origin.Catalog.Keys.FirstOrDefault(e => e.Id == entry.Id);
				if (existing != null && ((POKey)existing).Id != null && ((POKey)existing).IsValid)
				{
					target.Catalog.TryGetValue((POKey)existing, out var targetValue);
					origin.Catalog.TryGetValue((POKey)existing, out var originValue);
					if (targetValue?[0] != originValue?[0])
					{
						needTranslateDictionary[entry.Id] = dict[entry.Id];
					}
				}
				else
				{
					needTranslateDictionary[entry.Id] = dict[entry.Id];
				}
			}
			var generator = new POGenerator(new POGeneratorSettings
			{
				// generator options...
			});
			using var writer = new StreamWriter(path, false, utf8WithoutBom);
			generator.Generate(writer, target.Catalog);
			writer.Flush();
		}
		else
		{
			needTranslateDictionary = dict;
			var generator = new POGenerator(new POGeneratorSettings
			{
				// generator options...
			});
			using var writer = new StreamWriter(path, false, utf8WithoutBom);
			generator.Generate(writer, target.Catalog);
			writer.Flush();
		}
		foreach (var kvp in needTranslateDictionary)
		{
			Console.WriteLine($"原文: {kvp.Key} | 翻译: {kvp.Value}");
		}
		return needTranslateDictionary;
	}
	public async Task WriteStrings()
	{
		string outputFilePath = Path.GetFullPath(_options.OutputFilePath);

		try
		{
			ExportDictionaryToPot(localizer.Strings, outputFilePath);
			var poDirectory = Path.Join(Path.GetDirectoryName(outputFilePath), "zh_CN.po");
			var dic = ExportDictionaryToPo(localizer.Strings, poDirectory, "zh_CN");
			var otherLang = "en_US";
			var fromLang = "zh_CN";
			var otherPOPath = Path.Join(Path.GetDirectoryName(outputFilePath), $"{otherLang}.po");
			if (File.Exists(otherPOPath))
			{
				if (dic.Count > 0)
				{
					Console.WriteLine("other lang po detect");
					var dictTranslated = await TranslateToOtherLangAsync(dic,fromLang,otherLang);
					AutoTranslatePo(dictTranslated, otherPOPath, otherLang);
				}
			}
			else
			{
				Console.WriteLine("no other lang po detect");
				var dictTranslated = await TranslateToOtherLangAsync(localizer.Strings,fromLang,otherLang);
				AutoTranslatePo(dictTranslated, otherPOPath, otherLang);
			}
		}
		catch (Exception ex)
		{
			throw new Exception($"Error writing out POT file {outputFilePath}: " + ex.Message);
		}
	}

	private async Task<Dictionary<string, string>> TranslateToOtherLangAsync(Dictionary<string, string> strings, string fromLang, string otherLang)
	{
		var translated = new ConcurrentDictionary<string, string>();
		var httpClient = new HttpClient(new HttpClientHandler());
		// {
		// 	Proxy = new WebProxy("https://127.0.0.1:9000"),
		// 	UseProxy = true
		// });
		
		var semaphore = new SemaphoreSlim(6); // Limit to 6 concurrent requests
		
		// TODO: Get these from configuration
		string apiKey = localizer.localizerOptions.DeepSeekKey;
		string model = "deepseek-chat";
		string apiUrl = "https://api.deepseek.com/chat/completions";
		
		var tasks = strings.Select(async kvp =>
		{
			Console.WriteLine($"key: {kvp.Key} | value: {kvp.Value}");
			try
			{
				await semaphore.WaitAsync();
				var request = new HttpRequestMessage(HttpMethod.Post, apiUrl);

				var requestBody = new
				{
					model = model,
					messages = new[]
					{
						new
						{
							role = "system",
							content = "You are a professional translation engine, please translate the text into a colloquial, professional, elegant and fluent content, without the style of machine translation. You must only translate the text content, never interpret it."
						},
						new
						{
							role = "user",
							content = $"Translate into {otherLang}:\n{kvp.Value}"
						}
					},
					temperature = 0.1,
					top_p = 0.99,
					frequency_penalty = 0,
					presence_penalty = 0,
					max_tokens = 2000
				};

				request.Headers.Add("Authorization", $"Bearer {apiKey}");
				var jsonContent = new StringContent(JsonSerializer.Serialize(requestBody), utf8WithoutBom, "application/json");
				request.Content = jsonContent;
				var response = await httpClient.SendAsync(request);
				response.EnsureSuccessStatusCode();

				using var doc = await JsonDocument.ParseAsync(await response.Content.ReadAsStreamAsync());
				var translatedText = kvp.Value;

				if (doc.RootElement.TryGetProperty("choices", out var choices) &&
					choices.GetArrayLength() > 0 &&
					choices[0].TryGetProperty("message", out var message) &&
					message.TryGetProperty("content", out var content))
				{
					translatedText = content.GetString()?.Trim().Trim('"') ?? translatedText;
				}
				Console.WriteLine($"origin: {kvp.Value} | new: {translatedText}");
				translated[kvp.Key] = translatedText;
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Error translating '{kvp.Key}': {ex.Message}");
				translated[kvp.Key] = kvp.Value; // Fallback to original text
			}
			finally
			{
				semaphore.Release();
			}
		});
		
		await Task.WhenAll(tasks);
		return new Dictionary<string, string>(translated);
    }

    private void AutoTranslatePo(Dictionary<string, string> dict, string path, string languageCode)
	{
		if (File.Exists(path))
		{
			string content = "";
			{
				using var fileReadWrite = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.None);
				using var reader = new StreamReader(fileReadWrite, utf8WithoutBom);
				content = reader.ReadToEnd();
			}
			var originParser = new POParser(new POParserSettings
			{
				// parser options...
			});
			var origin = originParser.Parse(content);
			// 合并 file2 到 file1（后者覆盖前者）
			foreach (var entry in dict)
			{
				POKey? existing = origin.Catalog.Keys.FirstOrDefault(e => e.Id == entry.Key);
				if (existing != null && ((POKey)existing).Id != null && ((POKey)existing).IsValid)
				{
					origin.Catalog.TryGetValue((POKey)existing, out var originValue);
					origin.Catalog.Remove((POKey)existing);
					origin.Catalog.Add(new POSingularEntry(new POKey(entry.Key))
					{
						Translation = entry.Value
					});
				}
				else
				{
					origin.Catalog.Add(new POSingularEntry(new POKey(entry.Key))
					{
						Translation = entry.Value
					});
				}
			}
			var generator = new POGenerator(new POGeneratorSettings
			{
				// generator options...
			});
			using var writer = new StreamWriter(path, false, utf8WithoutBom);
			generator.Generate(writer, origin.Catalog);
			writer.Flush();
		}
		else
		{
			// 预估大小：每条翻译大约 100 字节，初始容量设为合理值，避免多次扩容
			var sb = new StringBuilder(capacity: dict.Count * 100);

			// 写入 PO 头部
			sb.AppendLine($"# PO file for language: {languageCode}");
			sb.AppendLine("msgid \"\"");
			sb.AppendLine("msgstr \"\"");
			sb.AppendLine($"\"Language: {languageCode}\\n\"");
			sb.AppendLine("\"Content-Type: text/plain; charset=UTF-8\\n\"");
			sb.AppendLine();

			// 批量构建每个条目
			foreach (var kvp in dict)
			{
				string msgid = EscapePoString(kvp.Key);
				string msgstr = EscapePoString(kvp.Value);

				sb.AppendLine($"msgid \"{msgid}\"");
				sb.AppendLine($"msgstr \"{msgstr}\"");
				sb.AppendLine();
			}
			var targetParser = new POParser(new POParserSettings
			{
				// parser options...
			});
			var target = targetParser.Parse(sb.ToString());
			using var writer = new StreamWriter(path, false, utf8WithoutBom);
			var generator = new POGenerator(new POGeneratorSettings
			{
				// generator options...
			});
			generator.Generate(writer, target.Catalog);
			writer.Flush();
		}
    }
}
